# 배치 단위 실행 설정
imageRoot: "/data/images/2025/08/27"  # 이미지 루트(날짜까지만), 글별 폴더는 콘텐츠ID 이름
outputDir: "./out"                    # 렌더된 HTML/로그 저장
storageStates:                         # Playwright 로그인 상태 파일
  naver_blog: ".auth/naver.json"
  tistory: ".auth/tistory.json"
  cafe24_blog: ".auth/cafe24.json"
  sonaverse_blog: ".auth/sonaverse.json"
  threads: ".auth/threads.json"
platforms:                            # 업로드 타겟 플랫폼들(키는 시트의 '플랫폼'과 동일)
  - naver_blog
  - tistory
  - cafe24_blog
  - sonaverse_blog
  - threads
headless: true                        # true면 브라우저 헤드리스
waitAfterPublishMs: 2000              # 게시 후 대기 (ms)